groups:
  # common: assets comuns a public e main
  moduleslayout.common:
    scripts:
      - bundles/moduleslayout/jquery/jquery.js

      - bundles/moduleslayout/angular/angular.js
      - bundles/moduleslayout/angular/angular-cookies.js
      - bundles/moduleslayout/angular/angular-cookies.min.js
      - bundles/moduleslayout/angular/angular-resources.js
      - bundles/moduleslayout/angular/angular-resources.min.js
      - bundles/moduleslayout/angular/angular-sanitize.js
      - bundles/moduleslayout/angular/angular-sanitize.min.js

      - bundles/moduleslayout/angular/i18n/angular-locale_en-us.js
      - bundles/moduleslayout/angular/i18n/angular-locale_es.js
      - bundles/moduleslayout/angular/i18n/angular-locale_pt-br.js

      - bundles/moduleslayout/angular-directives/angular-bDatepicker.js

      - bundles/moduleslayout/angular-ui/bootstrap/ui-bootstrap-custom-0.4.0-SNAPSHOT.js
      - bundles/moduleslayout/angular-ui/bootstrap/ui-bootstrap-custom-0.4.0-SNAPSHOT.min.js
      - bundles/moduleslayout/angular-ui/bootstrap/ui-bootstrap-custom-0.3.0-SNAPSHOT.js
      - bundles/moduleslayout/angular-ui/bootstrap/ui-bootstrap-custom-0.3.0-SNAPSHOT.min.js
      - bundles/moduleslayout/angular-ui/bootstrap/ui-bootstrap-custom-tpls-0.4.0-SNAPSHOT.js
      - bundles/moduleslayout/angular-ui/bootstrap/ui-bootstrap-custom-tpls-0.4.0-SNAPSHOT.min.js

      - bundles/moduleslayout/angular-ui/angular-ui.js
      - bundles/moduleslayout/angular-ui/angular-ui.min.js
      - bundles/moduleslayout/angular-ui/angular-ui.ieshiv.js
      - bundles/moduleslayout/angular-ui/angular-ui.ieshiv.min.js

      - bundles/moduleslayout/autocomplete/jquery.autocomplete.js
      - bundles/moduleslayout/autocomplete/jquery.autocomplete.min.js

      - bundles/moduleslayout/bootstrap/locales/bootstrap-datepicker-pt_BR.js

      - bundles/moduleslayout/bootstrap/bootstrap.js
      - bundles/moduleslayout/bootstrap/bootstrap.min.js
      - bundles/moduleslayout/bootstrap/bootstrap-alert.js
      - bundles/moduleslayout/bootstrap/bootstrap-button.js
      - bundles/moduleslayout/bootstrap/bootstrap-carousel.js
      - bundles/moduleslayout/bootstrap/bootstrap-collapse.js
      - bundles/moduleslayout/bootstrap/bootstrap-datatables.js
      - bundles/moduleslayout/bootstrap/bootstrap-datepicker.js
      - bundles/moduleslayout/bootstrap/bootstrap-dropdown.js
      - bundles/moduleslayout/bootstrap/bootstrap-modal.js
      - bundles/moduleslayout/bootstrap/bootstrap-popover.js
      - bundles/moduleslayout/bootstrap/bootstrap-scrollspy.js
      - bundles/moduleslayout/bootstrap/bootstrap-tab.js
      - bundles/moduleslayout/bootstrap/bootstrap-tooltip.js
      - bundles/moduleslayout/bootstrap/bootstrap-transition.js
      - bundles/moduleslayout/bootstrap/bootstrap-tupeahead.js

      - bundles/moduleslayout/bootstrap/jquery-1.7.2.min.js

      - bundles/fosjsrouting/js/router.js


